# Generated by Django 2.1.5 on 2019-05-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0050_auto_20181116_1029'),
        ('orgs', '0052_populate_org_uuid'),
    ]

    operations = [
    ]
