# Generated by Django 2.0.9 on 2019-01-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0050_auto_20181116_1029'),
        ('orgs', '0052_populate_org_uuid'),
    ]

    operations = [
    ]
