# Generated by Django 2.0.9 on 2019-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0130_auto_20181128_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='high_priority',
            field=models.NullBooleanField(help_text='Give this message higher priority than other messages'),
        ),
    ]
