# Generated by Django 2.1.3 on 2019-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0131_auto_20190108_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='high_priority',
            field=models.BooleanField(help_text='Give this message higher priority than other messages', null=True),
        ),
    ]
